### ISSUE TITLE
Hi,I found this plugin can't work

### ISSUE THREAD

**Issue by liuxiong21** [u-ichi/fluent-plugin-mail#16]
I want to send mail that mail body content get from fluentd log record's field value.

My configure is as follows：

```
<match error.**>
    type mail
    host smtp.exmail.qq.com #This is for Gmail and Google Apps. Any SMTP server should work
    port 25 #This is the port for smtp.gmail.com
    user liuxiong@souche.com #I work here! Use YOUR EMAIL.
    password lx2014 #I can't tell you this! Use YOUR PASSWORD!
    from xxxx@xxxx.com
    to xxxxx@xxxx.com
    subject Log Monitor Alert: %s
    subject_out_keys project
    out_keys msg,class,level
</match>
```

I receive email subject is:Log Monitor Alert:
content is:
msg: 
class: 
level:

**Comment by sonots** [comment]
Let me close.

**Comment by github-zhang** [comment]
have problems?

<match **.**>
  type mail
  host smtp.gmail.com
  port 587
  domain gmail.com
  from ****@gmail.com
  to *****@qq.com
  subject testsubjct
  user *****9@gmail.com
  password *****
  enable_starttls_auto true
  enable_tls false
  out_keys tag,foo,message
  time_locale UTC
</match>
