### ISSUE TITLE
delimeter problem with grepcounter plugin

### ISSUE THREAD

**Issue by glaci** [u-ichi/fluent-plugin-mail#17]
Hello author,

i've been encounter the problem with using fluentd grepcounter plugin

the default mail content type is text/plain
so the grepcounter delimeter parameter won't work

it shows like:

count: 4
message: [com.app.productmanagement.server.businessObject.ProductManagementBO] add product failed\n[com.app.productmanagement.server.businessObject.ProductManagementBO] add product failed\n[com.app.productmanagement.server.businessObject.ProductManagementBO] add product failed

the delimeter: \n will not work and display as pure text.
May you consider to add the option to setup mail content-type to text/html ?

**Comment by sonots** [comment]
Supporting `content_type` option sounds reasonable. PR is welcome!

**Comment by my-dev** [comment]
Hi! Mr.sonots

Thank You, Your Response.
I try it by now...f^^
