### ISSUE TITLE
String '[' is no available in Title???

### ISSUE THREAD

**Issue by my-dev** [u-ichi/fluent-plugin-mail#24]
Hi! Mr, sonots.

Yesterday, Thanks your nice support.

Today, once more question...please.

I can's use the string '['  in Title...
Even though i use the escape string '\', it's no expected.

In message, can use it normally.

this is no serious problem, but i wanna to use it...

please support me again sorry.

**Comment by sonots** [comment]
Paste the conf, what is `title`? Do you mean `subject`?

**Comment by my-dev** [comment]
Hi! Mr, sonots.

sorry, i meant [subject]...
this issue means below.

<match tag.mail.log>
	type mail
	host localhost
	port 25
	domain aiueo.com
	from alert@aiueo.com
	to aaa@bbb.ccc
	subject --->>>[<<<--- this issue means --->>>]<<<---tag.mail.log@%s
    subject_out_keys param1
	message [param2]：%s\n[param3]：%s\n[param4]：%s
    message_out_keys param2,param32,param4
	time_key time
	time_format %Y-%m-%d %H:%M:%S
</match>

in subject param, i can't use the string '[' and ']'.

**Comment by sonots** [comment]
In your case, rather, message is invalid. Try

```
type mail
host localhost
port 25
domain aiueo.com
from alert@aiueo.com
to aaa@bbb.ccc
subject --->>>[<<<--- this issue means --->>>]<<<---tag.mail.log@%s
subject_out_keys param1
message "[param2]：%s\n[param3]：%s\n[param4]：%s"
message_out_keys param2,param32,param4
time_key time
time_format %Y-%m-%d %H:%M:%S
```

I quoted `message` by `"`. 
This issue is coming from that fluentd v0.12 treats a value as JSON array if it starts with `[`. 

BTW: You can write a pre-formatted text with markdown like

    ```
    foobar
    ```

**Comment by my-dev** [comment]
Hi! Mr,sonots.

I will try later.

thank you.
